### PR TITLE
CMS-3158 php74 stable

### PR DESCRIPTION
**Pull request by dereuromark**
Ticket: https://spryker.atlassian.net/browse/CMS-3158

### CODE REVIEW

**Comment by alex-galych** [comment]
@Incognito Please also add Eco-CI for the testing and compatibility purpose.

**Review by alex-galych — CHANGES_REQUESTED** [review]
@Incognito Please also add Eco-CI for the testing and compatibility purpose.

**Comment by dereuromark** [comment]
any update here?

**Comment by Incognito** [comment]
Replaced by https://github.com/spryker-eco/coremedia/pull/8

**Pull request closed without merging**
